//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BingCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetOrders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetOrders()
        {
            this.AspNetOrderProducts = new HashSet<AspNetOrderProducts>();
        }
    
        public int OrderId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public double OrderFreight { get; set; }
        public double OrderTotalPrice { get; set; }
        public string UserId { get; set; }
        public int OrderRate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetOrderProducts> AspNetOrderProducts { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
