//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BingCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetCartProducts
    {
        public int CartProductId { get; set; }
        public string UserId { get; set; }
        public int ProductId { get; set; }


        public virtual AspNetProducts AspNetProducts { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
